include ../../defines.mak

OBJECTS =  \
        font.$(OBJ) hardsurf.$(OBJ) memsurf.$(OBJ) pen.$(OBJ) \
pentext.$(OBJ) screen.$(OBJ) surface.$(OBJ) viewport.$(OBJ)

OUTPUT = $(LIBDIR)2dlib.$(ARC)

include $(D3_LOCAL)/default.mak
