/*
 THE COMPUTER CODE CONTAINED HEREIN IS THE SOLE PROPERTY OF OUTRAGE
 ENTERTAINMENT, INC. ("OUTRAGE").  OUTRAGE, IN DISTRIBUTING THE CODE TO
 END-USERS, AND SUBJECT TO ALL OF THE TERMS AND CONDITIONS HEREIN, GRANTS A
 ROYALTY-FREE, PERPETUAL LICENSE TO SUCH END-USERS FOR USE BY SUCH END-USERS
 IN USING, DISPLAYING,  AND CREATING DERIVATIVE WORKS THEREOF, SO LONG AS
 SUCH USE, DISPLAY OR CREATION IS FOR NON-COMMERCIAL, ROYALTY OR REVENUE
 FREE PURPOSES.  IN NO EVENT SHALL THE END-USER USE THE COMPUTER CODE
 CONTAINED HEREIN FOR REVENUE-BEARING PURPOSES.  THE END-USER UNDERSTANDS
 AND AGREES TO THE TERMS HEREIN AND ACCEPTS THE SAME BY USE OF THIS FILE.
 COPYRIGHT 1996-2000 OUTRAGE ENTERTAINMENT, INC.  ALL RIGHTS RESERVED.
 */

// THESE SOUNDS MUST MATCH THE Static_sound_names[] array in SoundLoad.cpp

#define SOUND_NONE_INDEX 0 // the not-defined sound
#define SOUND_REFUELING 1
#define SOUND_ROBOT_EXPLODE_1 2
#define SOUND_ROBOT_EXPLODE_2 3
#define SOUND_BUILDING_EXPLODE 4
#define SOUND_BREAKING_GLASS 5
#define SOUND_MELEE_HIT_0 6
#define SOUND_MELEE_HIT_1 7
#define SOUND_AFTERBURNER 8
#define SOUND_ENERGY_DRAIN 9
#define SOUND_MISSLE_LOCK 10
#define SOUND_POWERUP_PICKUP 11
#define SOUND_DO_NOT_HAVE_IT 12
#define SOUND_CHANGE_PRIMARY 13
#define SOUND_CHANGE_SECONDARY 14
#define SOUND_PLAYER_HIT_WALL 15
#define SOUND_AFTERBURNER_TAIL 16
#define SOUND_FORCEFIELD_BOUNCE 17
#define SOUND_HEADLIGHT 18
#define SOUND_CHEATER 19
#define SOUND_ENERGY_CONVERTER 20
#define SOUND_COCKPIT 21
#define SOUND_METALLIC_DOOR_HIT 22
#define SOUND_WALL_FADE 23
#define SOUND_RAINDROP 24
#define SOUND_LIGHTNING 25
#define SOUND_HIT_BY_ENERGY_WEAPON 26
#define SOUND_HIT_BY_MATTER_WEAPON 27
#define SOUND_HIT_BY_CONCUSSIVE_FORCE 28
#define SOUND_PLAYER_BURNING 29
#define SOUND_MENU_SOUND_CLICK 30
#define SOUND_HOSTAGE_PICKUP 31
#define SOUND_BRIEF_STARTUP 32
#define SOUND_BRIEF_STATIC 33
#define SOUND_BRIEF_MONITOROFF 34
#define SOUND_BRIEF_RUNNING 35
#define SOUND_BRIEF_BULLB 36
#define SOUND_BRIEF_TYPE 37
#define SOUND_SHIP_IDLE 38
#define SOUND_SHIP_FORWARD_THRUST 39
#define SOUND_SHIP_FORWARD_RELEASE 40
#define SOUND_GOAL_COMPLETE 41
#define SOUND_DEBRIS_EXPLODE 42
#define SOUND_GAME_MESSAGE 43
#define SOUND_CHANGE_COUNTERMEASURE 44
#define SOUND_CHANGE_INVENTORY 45
#define SOUND_VOLATILE_HISS 46
#define SOUND_WEAPON_HIT_LAVA 47
#define SOUND_WEAPON_HIT_WATER 48
#define NUM_STATIC_SOUNDS 49 // update this every time you add a new sound
