/*
 THE COMPUTER CODE CONTAINED HEREIN IS THE SOLE PROPERTY OF OUTRAGE
 ENTERTAINMENT, INC. ("OUTRAGE").  OUTRAGE, IN DISTRIBUTING THE CODE TO
 END-USERS, AND SUBJECT TO ALL OF THE TERMS AND CONDITIONS HEREIN, GRANTS A
 ROYALTY-FREE, PERPETUAL LICENSE TO SUCH END-USERS FOR USE BY SUCH END-USERS
 IN USING, DISPLAYING,  AND CREATING DERIVATIVE WORKS THEREOF, SO LONG AS
 SUCH USE, DISPLAY OR CREATION IS FOR NON-COMMERCIAL, ROYALTY OR REVENUE
 FREE PURPOSES.  IN NO EVENT SHALL THE END-USER USE THE COMPUTER CODE
 CONTAINED HEREIN FOR REVENUE-BEARING PURPOSES.  THE END-USER UNDERSTANDS
 AND AGREES TO THE TERMS HEREIN AND ACCEPTS THE SAME BY USE OF THIS FILE.
 COPYRIGHT 1996-2000 OUTRAGE ENTERTAINMENT, INC.  ALL RIGHTS RESERVED.
 */
#ifndef WEAPON_EXTERNAL_H_
#define WEAPON_EXTERNAL_H_

#define LASER_INDEX 0
#define VAUSS_INDEX 1
#define MICROWAVE_INDEX 2
#define PLASMA_INDEX 3
#define FUSION_INDEX 4
#define SUPER_LASER_INDEX 5
#define MASSDRIVER_INDEX 6
#define NAPALM_INDEX 7
#define EMD_INDEX 8
#define OMEGA_INDEX 9
#define CONCUSSION_INDEX 10
#define HOMING_INDEX 11
#define IMPACTMORTAR_INDEX 12
#define SMART_INDEX 13
#define MEGA_INDEX 14
#define FRAG_INDEX 15
#define GUIDED_INDEX 16
#define NAPALMROCKET_INDEX 17
#define CYCLONE_INDEX 18
#define BLACKSHARK_INDEX 19

#define FLARE_INDEX 20

#endif